  class GameOverException(Exception):
    """Исключение, вызываемое при завершении игры."""
    pass
